config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome"

  resources :captains
  get '/captain/login' => "captains#login"
  post '/captain/login' => "captains#create"

  resources :ports

  resources :passengers do
    resources :excursions do
      resources :passenger_excursions
    end
  end

  get '/passenger_excursions/most_recent' => "passenger_excursions#show"
  get '/login' => "passengers#login"
  post '/login' => "passengers#create"
  get '/logout' => "passengers#logout"
  get '/fb_login' => "passengers#fb_login"
  post '/fb_login' => "passengers#fb_create"
  get '/auth/facebook/callback' => 'passengers#create'

  get '/passengers/:passenger_id/ports' => 'passengers#ports'
  post '/passengers/:passenger_id/excursions/:excursion_id/passenger_excursions/:id' => "passenger_excursions#update"

  get '/passengers/:passenger_id/excursions/:excursion_id/passenger_excursions/:id/delete' => "passenger_excursions#delete"

  resources :ships, only: [:index, :new, :create, :edit, :update, :destroy]

  get '/ships/largest_ship' => "ships#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/captain.rb
class Captain < ApplicationRecord
  has_secure_password

  has_many :ships

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :password, presence: true
  validates :secret_phrase, inclusion: {in: %w(ipromise)} 

end

app/controllers/captains_controller.rb
class CaptainsController < ApplicationController

  def new
    @captain = Captain.new
  end

  def create
    if params[:captain]
      @captain = Captain.new(captain_params)
      if @captain.save
        set_session_id
      else
        set_flash_alerts
        redirect_to new_captain_path
      end
    else
      if @captain = Captain.find_by(name: params[:name])
        if @captain.authenticate(params[:password])
          set_session_id
        else
          cannot_find_account
        end
      else
        cannot_find_account
      end
    end
  end

  def show
    @captain = Captain.find(session[:captain_id])
    if !!check_current_user
    else
      redirect_to root_path
    end
  end

  def login
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def captain_params
    params.require(:captain).permit(:name, :password, :secret_phrase)
  end

  def set_session_id
    session[:captain_id] = @captain.id
    redirect_to captain_path(@captain)
  end

  def cannot_find_account
    flash[:alert] = "We cannot find your account in our system... Please try again."
    redirect_to captain_login_path
  end

  def error_messages
    @alert = []
    @captain.errors.full_messages.each do |m|
      @alert << m
    end
    @alert
  end

  def set_flash_alerts
    flash[:alert1] = "#{error_messages[0]}"
    flash[:alert2] = "#{error_messages[1]}"
    flash[:alert3] = "#{error_messages[2]}"
  end

end

app/helpers/captains_helper.rb
module CaptainsHelper
end

app/views/captains/_form_new_captain.html.erb
<%=form_for(captain) do |f|%>
  <%=f.label :name%>
  <%=f.text_field :name%><br>
  <%=f.label :password%>
  <%=f.text_field :password%><br>
  <%=f.label "Captain Secret Phrase"%>
  <%=f.text_field :secret_phrase%><br><br>
  <%=f.submit%>
<%end%>

app/views/captains/login.html.erb
<h1>Captain Login:</h1>

<%= render partial: "passengers/form_login", locals: {login_path: captain_login_path} %><br><br>

app/views/captains/new.html.erb
<h1>New Captain:</h1>

<%= render partial: "form_new_captain", locals: {captain: @captain} %>

app/views/captains/show.html.erb
<h1>Welcome <%=@captain.name%></h1>

<h2>Your Ships:</h2>
<%@captain.ships.each do |ship|%>
  <h3><%=ship.name%> - <%=link_to("Edit", edit_ship_path(ship))%></h3>

  <%= render partial: "ships/ship_info", locals: {ship: ship} %>

<%end%>

<%=link_to("Create New Ship", new_ship_path)%>