config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome"

  resources :captains
  get '/captain/login' => "captains#login"
  post '/captain/login' => "captains#create"

  resources :ports

  resources :passengers do
    resources :excursions do
      resources :passenger_excursions
    end
  end

  get '/passenger_excursions/most_recent' => "passenger_excursions#show"
  get '/login' => "passengers#login"
  post '/login' => "passengers#create"
  get '/logout' => "passengers#logout"
  get '/fb_login' => "passengers#fb_login"
  post '/fb_login' => "passengers#fb_create"
  get '/auth/facebook/callback' => 'passengers#create'

  get '/passengers/:passenger_id/ports' => 'passengers#ports'
  post '/passengers/:passenger_id/excursions/:excursion_id/passenger_excursions/:id' => "passenger_excursions#update"

  get '/passengers/:passenger_id/excursions/:excursion_id/passenger_excursions/:id/delete' => "passenger_excursions#delete"

  resources :ships, only: [:index, :new, :create, :edit, :update, :destroy]

  get '/ships/largest_ship' => "ships#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/passenger.rb
class Passenger < ApplicationRecord

  has_secure_password
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :password, presence: true


  belongs_to :ship
  has_many :passenger_excursions
  has_many :excursions, through: :passenger_excursions
  has_many :ports, through: :excursions

  def total_excursion_time
    @total = 0
    self.excursions.each do |e|
      @total += e.duration
    end
    @total
  end

end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController

  def new
    @passenger = Passenger.new
  end

  def create
    if params[:passenger]
      @passenger = Passenger.new(passenger_params)
      if @passenger.save
        set_session_id
      else
        set_flash_alerts
        render "new"
      end
    elsif auth
      if @passenger = Passenger.find_by(uid: auth[:uid])
        set_session_id
      else
        fb_setup
        set_session_id
      end
    else
      if @passenger = Passenger.find_by(name: params[:name])
        if @passenger.authenticate(params[:password])
          set_session_id
        else
          cannot_find_account
        end
      else
        cannot_find_account
      end
    end
  end

  def show
    @passenger = Passenger.find(params[:id])
    @excursions = @passenger.excursions
    if !!check_current_user
    else
      redirect_to root_path
    end
  end

  def ports
    @passenger = Passenger.find(params[:passenger_id])
    @ports = @passenger.ports
    @uniq_ports = @ports.map {|port| port.location}
    @uniq_ports = @uniq_ports.uniq
    render json: @uniq_ports
  end

  def login
  end

  def fb_login
  end

  def fb_create
    session[:ship_id] = params[:passenger][:ship_id]
    redirect_to '/auth/facebook'
  end

  def logout
    session[:user_id] = nil
    session[:captain_id] = nil
    redirect_to root_path
  end

  private

  def passenger_params
    params.require(:passenger).permit(:name, :password, :ship_id)
  end

  def error_messages
    @alert = []
    @passenger.errors.full_messages.each do |m|
      @alert << m
    end
    @alert
  end

  def auth
    request.env['omniauth.auth']
  end

  def set_session_id
    session[:user_id] = @passenger.id
    redirect_to passenger_path(@passenger)
  end

  def fb_setup
    @passenger = Passenger.new
    @passenger.uid = auth[:uid]
    @passenger.name = auth[:info][:name]
    @passenger.password = SecureRandom.hex
    @passenger.ship_id = session[:ship_id].to_i
    @passenger.save
  end

  def set_flash_alerts
    flash[:alert1] = "#{error_messages[0]}"
    flash[:alert2] = "#{error_messages[1]}"
    flash[:alert3] = "#{error_messages[2]}"
  end

  def cannot_find_account
    flash[:alert] = "We cannot find your account in our system... Please try again."
    redirect_to login_path
  end

end

app/helpers/passengers_helper.rb
module PassengersHelper

  def ship_captain(passenger)
    @captain = Captain.find_by(id: passenger.ship.captain_id)
    @captain.name
  end

  def pluralize_hours(passenger)
    pluralize(passenger.total_excursion_time, "hour")
  end
end

app/views/passengers/_excursions.html.erb
<ul class="ul_excursions">
  <%excursions.each do |e|%>
    <% if find_pe(passenger, e)[0].comment != "" && find_pe(passenger, e)[0].comment != nil%>
      <li class="excursion_info id_<%=e.id%>"><%=e.title%> - <%=e.port.location%> - <%=excursion_pluralize(e)%> - <span class="link add_comment" onclick="addComment(<%=passenger.id%>, <%=e.id%>, <%=find_pe(passenger, e)[0].id%>)">Edit Comment</span> - <span class="link delete_link" onclick="deleteExcursion(<%=passenger.id%>, <%=e.id%>)">Delete</span> </li>
        <div class="divChild_<%=e.id%>">
          <ul>
            <div class="commentList_<%=e.id%>">
              <li class="comment_<%=find_pe(passenger, e)[0].id%>">
                <span><%=find_pe(passenger, e)[0].comment%></span>
                <span> - </span>
                <span class="link" onclick="deleteComment(<%=passenger.id%>, <%=e.id%>, <%=find_pe(passenger, e)[0].id%>)">Delete</span>
              </li>
            </div>
          </ul>

        </div>
      <%else%>
        <li class="excursion_info id_<%=e.id%>"><%=e.title%> - <%=e.port.location%> - <%=excursion_pluralize(e)%> - <span class="link add_comment" data-id="<%=e.id%>" onclick="addComment(<%=passenger.id%>, <%=e.id%>, <%=find_pe(passenger, e)[0].id%>)">Add Comment</span> - <span class="link delete_link"  onclick="deleteExcursion(<%=passenger.id%>, <%=e.id%>)">Delete</span></li>
        <div class="divChild_<%=e.id%>">
          <ul>
            <div class="commentList_<%=e.id%>">
            </div>
          </ul>

        </div>
    <%end%>
  <%end%>
</ul>

app/views/passengers/_form_login.html.erb
<div class="login-form">
<%=form_tag login_path do %>
  <%=label_tag :username%>
  <%=text_field_tag :name%><br>
  <%=label_tag :password%>
  <%=text_field_tag :password%><br>
  <%=submit_tag "Login", class: "login-submit"%>
<%end%>
</div>

app/views/passengers/_form_new.html.erb
<div class="login-form">
<%=form_for(passenger) do |f|%>
  <%=f.label "Ship"%>
  <%=f.collection_select(:ship_id, Ship.all, :id, :name, {include_blank: ""})%><br><br>
  <%=f.label :username%>
  <%=f.text_field :name%><br>
  <%=f.label :password%>
  <%=f.text_field :password%><br><br>
  <%=f.submit "Create Account", class: "login-submit"%>
<%end%>
</div>

app/views/passengers/fb_login.html.erb
<h1>To Login with Facebook, Please Choose a Ship: </h1>

<%=form_tag fb_login_path do%>
  <%=label_tag "Ship"%>
  <%=collection_select(:passenger, :ship_id, Ship.all, :id, :name, {include_blank: ""})%><br><br>
  <%=submit_tag "Login with Facebook"%>
<%end%>

app/views/passengers/login.html.erb
<h1>Login:</h1>

<%= render "form_login" %>
<br><br>
<!-- <%=link_to("Log in with Facebook!", fb_login_path)%> -->
<a class="facebook" href="/fb_login">Log in with Facebook!</a>

app/views/passengers/new.html.erb
<h1>Create a new Account:</h1>

<%= render partial: "form_new", locals: {passenger: @passenger} %><br><br>

<!-- <%=link_to("Captain Form", new_captain_path)%> -->

app/views/passengers/show.html.erb
<div class="passenger-box">
  <h1 class="passenger_name" data-id="<%=@passenger.id%>">Welcome <%=@passenger.name%>!</h1>

  <h3>Your Ship is: <%=@passenger.ship.name%></h3>

  <h3>Your Captain is: <%=ship_captain(@passenger)%></h3>

  <h3>Your Excursions:</h3>

  <%= render partial: "excursions", locals: {excursions: @excursions, passenger: @passenger, passenger_excursion: @passenger_excursion} %>

    <span class="link ports_link" onclick="showPorts(<%=@passenger.id%>)">Show Ports</span>
    <div class="ports">
    </div>


  <h3 class="total_time">Total Excursion Time: <%=pluralize_hours(@passenger)%>.</h3>
</div>
<div class="add_excursion_div">
  <span class="link add_excursion" onclick="addExcursion()">Add Excursion</span>
  <!-- <%=link_to("Add Excursion", new_passenger_excursion_path(@passenger))%><br> -->
</div>