config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome"

  resources :captains
  get '/captain/login' => "captains#login"
  post '/captain/login' => "captains#create"

  resources :ports

  resources :passengers do
    resources :excursions do
      resources :passenger_excursions
    end
  end

  get '/passenger_excursions/most_recent' => "passenger_excursions#show"
  get '/login' => "passengers#login"
  post '/login' => "passengers#create"
  get '/logout' => "passengers#logout"
  get '/fb_login' => "passengers#fb_login"
  post '/fb_login' => "passengers#fb_create"
  get '/auth/facebook/callback' => 'passengers#create'

  get '/passengers/:passenger_id/ports' => 'passengers#ports'
  post '/passengers/:passenger_id/excursions/:excursion_id/passenger_excursions/:id' => "passenger_excursions#update"

  get '/passengers/:passenger_id/excursions/:excursion_id/passenger_excursions/:id/delete' => "passenger_excursions#delete"

  resources :ships, only: [:index, :new, :create, :edit, :update, :destroy]

  get '/ships/largest_ship' => "ships#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ship.rb
class Ship < ApplicationRecord
  has_many :passengers
  belongs_to :captain

  validates :name, presence: true
  # validates :name, uniqueness: true
  validates :capacity, presence: true
  validates :number_of_swimming_pools, presence: true

  def self.largest_ship
    Ship.order("capacity DESC").limit(1)[0]
  end

end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController

  def new
    @ship = Ship.new
  end

  def create
    @ship = Ship.new(ship_params)
    @ship.captain_id = current_user_instance.id
    if @ship.save
      redirect_to captain_path(current_user_instance)
    else
      set_flash_alerts
      redirect_to new_ship_path
    end

  end

  def index
    @ships = Ship.all
    render json: @ships 
  end

  def show
    @ship = Ship.largest_ship
  end

  def edit
    @ship = Ship.find(params[:id])
  end

  def update
    @ship = Ship.find_by(id: params[:id].to_i)
    @ship.update(ship_params)
    redirect_to captain_path(current_user_instance)
  end

  def destroy
    @ship = Ship.find(params[:id])
    @ship.delete
    redirect_to captain_path(current_user_instance)
  end

  private

  def ship_params
    params.require(:ship).permit(:name, :capacity, :number_of_swimming_pools, :kid_friendly, :casino, :zip_line)
  end

  # def update_params
  #   params.require(:ship).permit(:capacity, :number_of_swimming_pools, :kid_friendly, :casino, :zip_line)
  # end

  def error_messages
    @alert = []
    @ship.errors.full_messages.each do |m|
      @alert << m
    end
    @alert
  end

  def set_flash_alerts
    flash[:alert1] = "#{error_messages[0]}"
    flash[:alert2] = "#{error_messages[1]}"
    flash[:alert3] = "#{error_messages[2]}"
  end


end

app/helpers/ships_helper.rb
module ShipsHelper

  def largest_ship
    Ship.largest_ship
  end
end

app/views/ships/_form_new_ship.html.erb
<%=form_for(ship) do |f|%>
  <%=f.label "Name"%>
  <%=f.text_field :name%><br>
  <%=f.label :capacity%>
  <%=f.text_field :capacity%><br>
  <%=f.label "number_of_swimming_pools"%>
  <%=f.text_field :number_of_swimming_pools%><br>
  <%=f.label "zip_line"%>
  <%=f.check_box :zip_line%><br>
  <%=f.label "kid_friendly"%>
  <%=f.check_box :kid_friendly%><br>
  <%=f.label "Casino"%>
  <%=f.check_box :casino%><br><br>
  <%=f.submit "Submit"%>
<%end%>

app/views/ships/_ship_info.html.erb
<ul>
  <li>Capacity: <%=ship.capacity%></li>
  <li>Number of Swimming Pools: <%=ship.number_of_swimming_pools%></li>
  <li>Zip Line: <%=ship.zip_line%></li>
  <li>Kid Friendly: <%=ship.kid_friendly%></li>
  <li>Casino: <%=ship.casino%></li>
</ul>

app/views/ships/edit.html.erb
<h1>Edit Ship: <%=@ship.name%></h1>

<%= render partial: "form_new_ship", locals: {ship: @ship} %>

<br>
<%= button_to "Delete", ship_path(@ship), {method: :delete} %>

app/views/ships/index.html.erb
<h1>All Available Ships:</h1>


<%@ships.each do |ship|%>
    <h3><%=ship.name%> - Captain: <%=ship.captain.name%></h3>
    <%= render partial: "ship_info", locals: {ship: ship} %>
<%end%>
<br>
<!-- <%=link_to("Largest Ship", ships_largest_ship_path)%>
<link rel="stylesheet" href="/ships/largest_ship"> -->

<a class="largest_ship_link" href="/ships/largest_ship">Largest Ship</a>

app/views/ships/new.html.erb
<h1>Create New Cruise Ship:</h1>

<%= render partial: "form_new_ship", locals: {ship: @ship} %>

app/views/ships/show.html.erb
<h1>Our Largest Ship is: <%=@ship.name%></h1>

<%= render partial: "ship_info", locals: {ship: @ship} %>