config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome"

  resources :captains
  get '/captain/login' => "captains#login"
  post '/captain/login' => "captains#create"

  resources :ports

  resources :passengers do
    resources :excursions do
      resources :passenger_excursions
    end
  end

  get '/passenger_excursions/most_recent' => "passenger_excursions#show"
  get '/login' => "passengers#login"
  post '/login' => "passengers#create"
  get '/logout' => "passengers#logout"
  get '/fb_login' => "passengers#fb_login"
  post '/fb_login' => "passengers#fb_create"
  get '/auth/facebook/callback' => 'passengers#create'

  get '/passengers/:passenger_id/ports' => 'passengers#ports'
  post '/passengers/:passenger_id/excursions/:excursion_id/passenger_excursions/:id' => "passenger_excursions#update"

  get '/passengers/:passenger_id/excursions/:excursion_id/passenger_excursions/:id/delete' => "passenger_excursions#delete"

  resources :ships, only: [:index, :new, :create, :edit, :update, :destroy]

  get '/ships/largest_ship' => "ships#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CruiseShip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="header">
    <a id="home_link" class="links" href="<%=root_path%>">Home</a>
    <%if logged_in?%>
    <a class="links" href="<%=current_user_path%>"><%=current_user%></a>
    <a class="links" href="<%=logout_path%>">Logout</a>
    <%else %>
      <a class="links" href="<%=login_path%>">Login</a>
      <!-- <a class="links" href="<%=captain_login_path%>">Captain Login</a> -->
      <a class="links" href="<%=new_passenger_path%>">Sign Up</a>
    <%end%>

  </div>
  <body class="body">

    <!-- <div class="inner_body"> -->
        <!-- <%= image_tag("beach.jpg", :alt => "beach", :class => "ad_img") %> -->
    <!-- </div> -->

    <% flash.each do |name, msg| -%>
       <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>

  </body>
  <footer>
    <div class="">
      © 2018 Cruise Navigator
    </div>
  </footer>
</html>

app/views/layouts/welcome.html.erb
<h1>Welcome to your Cruise Navigator!</h1>

<br>
<div class="all_ships">
  <span onclick="learnLink()"><%= image_tag("ship.png", :alt => "Cruise Ship", :class => "ship-img") %></span> 

  <!-- <img class="ship-img" onclick="learnLink()" src="https://dumielauxepices.net/sites/default/files/monitor-lizard-clipart-transparent-background-686908-3653187.png" alt="Cruise Ship"> -->

  <div class="advertising-box clearfix">
    <div class="advertising-img">
      <%= image_tag("labadee.png", :alt => "labadee", :class => "ad-img") %>
      <!-- <img class="ad-img" src='assets/labadee.png' alt="Labadee"> -->
      <span>Labadee</span>
    </div>
    <div class="advertising-img">
      <%= image_tag("bahamas.png", :alt => "bahamas", :class => "ad-img") %>
      <!-- <img class="ad-img" src="assets/bahamas.png" alt="Bahamas"> -->
      <span>Bahamas</span>
    </div>
    <div class="advertising-img">
      <%= image_tag("marteen.png", :alt => "marteen", :class => "ad-img") %>
      <!-- <img class="ad-img" src="assets/marteen.png" alt="St. Maarten"> -->
      <span>St. Maarten</span>
    </div>
  </div>
  <!-- <span class="link learn_link" onclick="learnLink()">Learn about the differnet ships</span> -->
</div>
<div class="largest_ship">

</div>